GET http://localhost:5000


### Check Server Status


GET http://localhost:5000/api


### Get all Users
GET http://localhost:5000/api/v1/users
x-api-key: jUG9rrf8Zx5zYtFTJmyzvqaGjS9njBhacRGZhFSjHsQUw5g9yrPHJsH55mz4Z62n


### Get particular User
GET http://localhost:5000/api/v1/users/5e3ffba65bad3a38dc0509cd
x-api-key: jUG9rrf8Zx5zYtFTJmyzvqaGjS9njBhacRGZhFSjHsQUw5g9yrPHJsH55mz4Z62n


### Register User / Add User
POST http://localhost:5000/api/v1/users
x-api-key: jUG9rrf8Zx5zYtFTJmyzvqaGjS9njBhacRGZhFSjHsQUw5g9yrPHJsH55mz4Z62n
Content-Type: application/json

{
    "name": "Ekansh Jain",
    "email": "ejekanshjain@gmail.com",
    "password": "password"
}


### Login User
POST http://localhost:5000/api/v1/login
x-api-key: jUG9rrf8Zx5zYtFTJmyzvqaGjS9njBhacRGZhFSjHsQUw5g9yrPHJsH55mz4Z62n
Content-Type: application/json

{
    "email": "ejekanshjain@gmail.com",
    "password": "password"
}


### Update User
PATCH http://localhost:5000/api/v1/users
x-api-key: jUG9rrf8Zx5zYtFTJmyzvqaGjS9njBhacRGZhFSjHsQUw5g9yrPHJsH55mz4Z62n
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODE3ODgzNDYsImRhdGEiOnsiX2lkIjoiNWUzZmZiYTY1YmFkM2EzOGRjMDUwOWNkIiwibmFtZSI6IkVrYW5zaCBKYWluIiwiZW1haWwiOiJlamVrYW5zaGphaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkbEYxZXZ1SmdmQzBON2ZJQzRJN0tyT0cubHE1NmFpSHpuZElZd2MvWVJiM2F1TFRnSGZtR0siLCJjcmVhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJ1cGRhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJfX3YiOjB9LCJpYXQiOjE1ODE3MDE5NDZ9.pDTx-YMCOLh-BLTM4QyEAdqRKBOmAd2dD1kjhrs95b8
Content-Type: application/json

{
    "name": "Ekansh Jain",
    "email": "ejekanshjain@gmail.com"
}


### Get all Posts for Newsfeed Homepage
GET http://localhost:5000/api/v1/posts?feed=true
x-api-key: jUG9rrf8Zx5zYtFTJmyzvqaGjS9njBhacRGZhFSjHsQUw5g9yrPHJsH55mz4Z62n
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODE3ODgzNDYsImRhdGEiOnsiX2lkIjoiNWUzZmZiYTY1YmFkM2EzOGRjMDUwOWNkIiwibmFtZSI6IkVrYW5zaCBKYWluIiwiZW1haWwiOiJlamVrYW5zaGphaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkbEYxZXZ1SmdmQzBON2ZJQzRJN0tyT0cubHE1NmFpSHpuZElZd2MvWVJiM2F1TFRnSGZtR0siLCJjcmVhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJ1cGRhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJfX3YiOjB9LCJpYXQiOjE1ODE3MDE5NDZ9.pDTx-YMCOLh-BLTM4QyEAdqRKBOmAd2dD1kjhrs95b8


### Get all Posts of logged in user
GET http://localhost:5000/api/v1/posts
x-api-key: jUG9rrf8Zx5zYtFTJmyzvqaGjS9njBhacRGZhFSjHsQUw5g9yrPHJsH55mz4Z62n
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODE3ODgzNDYsImRhdGEiOnsiX2lkIjoiNWUzZmZiYTY1YmFkM2EzOGRjMDUwOWNkIiwibmFtZSI6IkVrYW5zaCBKYWluIiwiZW1haWwiOiJlamVrYW5zaGphaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkbEYxZXZ1SmdmQzBON2ZJQzRJN0tyT0cubHE1NmFpSHpuZElZd2MvWVJiM2F1TFRnSGZtR0siLCJjcmVhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJ1cGRhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJfX3YiOjB9LCJpYXQiOjE1ODE3MDE5NDZ9.pDTx-YMCOLh-BLTM4QyEAdqRKBOmAd2dD1kjhrs95b8


### Get all Posts of a particular user
GET http://localhost:5000/api/v1/posts?user=5e403dcd1000793694bd2276
x-api-key: jUG9rrf8Zx5zYtFTJmyzvqaGjS9njBhacRGZhFSjHsQUw5g9yrPHJsH55mz4Z62n
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODE3ODgzNDYsImRhdGEiOnsiX2lkIjoiNWUzZmZiYTY1YmFkM2EzOGRjMDUwOWNkIiwibmFtZSI6IkVrYW5zaCBKYWluIiwiZW1haWwiOiJlamVrYW5zaGphaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkbEYxZXZ1SmdmQzBON2ZJQzRJN0tyT0cubHE1NmFpSHpuZElZd2MvWVJiM2F1TFRnSGZtR0siLCJjcmVhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJ1cGRhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJfX3YiOjB9LCJpYXQiOjE1ODE3MDE5NDZ9.pDTx-YMCOLh-BLTM4QyEAdqRKBOmAd2dD1kjhrs95b8


### Get a particular Post
GET http://localhost:5000/api/v1/posts/5e403e8b1000793694bd2278
x-api-key: jUG9rrf8Zx5zYtFTJmyzvqaGjS9njBhacRGZhFSjHsQUw5g9yrPHJsH55mz4Z62n
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODE3ODgzNDYsImRhdGEiOnsiX2lkIjoiNWUzZmZiYTY1YmFkM2EzOGRjMDUwOWNkIiwibmFtZSI6IkVrYW5zaCBKYWluIiwiZW1haWwiOiJlamVrYW5zaGphaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkbEYxZXZ1SmdmQzBON2ZJQzRJN0tyT0cubHE1NmFpSHpuZElZd2MvWVJiM2F1TFRnSGZtR0siLCJjcmVhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJ1cGRhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJfX3YiOjB9LCJpYXQiOjE1ODE3MDE5NDZ9.pDTx-YMCOLh-BLTM4QyEAdqRKBOmAd2dD1kjhrs95b8


### Add Post / Create Post
POST http://localhost:5000/api/v1/posts
x-api-key: jUG9rrf8Zx5zYtFTJmyzvqaGjS9njBhacRGZhFSjHsQUw5g9yrPHJsH55mz4Z62n
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODE3ODgzNDYsImRhdGEiOnsiX2lkIjoiNWUzZmZiYTY1YmFkM2EzOGRjMDUwOWNkIiwibmFtZSI6IkVrYW5zaCBKYWluIiwiZW1haWwiOiJlamVrYW5zaGphaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkbEYxZXZ1SmdmQzBON2ZJQzRJN0tyT0cubHE1NmFpSHpuZElZd2MvWVJiM2F1TFRnSGZtR0siLCJjcmVhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJ1cGRhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJfX3YiOjB9LCJpYXQiOjE1ODE3MDE5NDZ9.pDTx-YMCOLh-BLTM4QyEAdqRKBOmAd2dD1kjhrs95b8
Content-Type: application/json

{
    "title": "Post One",
    "body": "this is my first post's body"
}


### Update Post
PATCH http://localhost:5000/api/v1/posts/5e4770e3aac2291f748a26de
x-api-key: jUG9rrf8Zx5zYtFTJmyzvqaGjS9njBhacRGZhFSjHsQUw5g9yrPHJsH55mz4Z62n
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODE3ODgzNDYsImRhdGEiOnsiX2lkIjoiNWUzZmZiYTY1YmFkM2EzOGRjMDUwOWNkIiwibmFtZSI6IkVrYW5zaCBKYWluIiwiZW1haWwiOiJlamVrYW5zaGphaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkbEYxZXZ1SmdmQzBON2ZJQzRJN0tyT0cubHE1NmFpSHpuZElZd2MvWVJiM2F1TFRnSGZtR0siLCJjcmVhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJ1cGRhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJfX3YiOjB9LCJpYXQiOjE1ODE3MDE5NDZ9.pDTx-YMCOLh-BLTM4QyEAdqRKBOmAd2dD1kjhrs95b8
Content-Type: application/json

{
    "title": "Updated Title",
    "body": "Updated Body"
}


### Delete Post
DELETE http://localhost:5000/api/v1/posts/5e46db87d4417a3138978cca
x-api-key: jUG9rrf8Zx5zYtFTJmyzvqaGjS9njBhacRGZhFSjHsQUw5g9yrPHJsH55mz4Z62n
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1ODE3ODgzNDYsImRhdGEiOnsiX2lkIjoiNWUzZmZiYTY1YmFkM2EzOGRjMDUwOWNkIiwibmFtZSI6IkVrYW5zaCBKYWluIiwiZW1haWwiOiJlamVrYW5zaGphaW5AZ21haWwuY29tIiwicGFzc3dvcmQiOiIkMmEkMTAkbEYxZXZ1SmdmQzBON2ZJQzRJN0tyT0cubHE1NmFpSHpuZElZd2MvWVJiM2F1TFRnSGZtR0siLCJjcmVhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJ1cGRhdGVkQXQiOiIyMDIwLTAyLTA5VDEyOjMxOjM0LjExN1oiLCJfX3YiOjB9LCJpYXQiOjE1ODE3MDE5NDZ9.pDTx-YMCOLh-BLTM4QyEAdqRKBOmAd2dD1kjhrs95b8


###
